name: Package - Unit Tests
on:
  workflow_dispatch:
    inputs:
      package:
        description: package name
        required: true
        type: string
jobs:
    build:
        runs-on: [self-hosted, demand]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install dependencies
              working-directory: '"./packages/${{ inputs.package }}"'
              run: npm ci

            - name: Run unit tests
              working-directory: '"./packages/${{ inputs.package }}"'
              run: npm run test 
